export const ratings = [
  {
    id: 1,
    name: 'John Doe',
    rating: 4.0,
    testimony: 'Great service and quality products! Highly recommend.',
    date: 'Published on June, 2024',
  },
  {
    id: 2,
    name: 'Jane Smith',
    rating: 4.0,
    testimony: 'The products arrived on time and in good condition.',
    date: 'Published on June, 2024',
  },
  {
    id: 3,
    name: 'Alex Johnson',
    rating: 4.0,
    testimony: 'Amazing experience! Will shop again.',
    date: 'Published on June, 2024',
  },
  {
    id: 4,
    name: 'Maria Garcia',
    rating: 4.0,
    testimony: 'Good products, but shipping could be faster.',
    date: 'Published on June, 2024',
  },
  {
    id: 5,
    name: 'David Brown',
    rating: 4.0,
    testimony: 'Loved the variety of products available!',
    date: 'Published on June, 2024',
  },
  {
    id: 6,
    name: 'Lisa White',
    rating: 4.0,
    testimony: 'Customer support was very helpful. Highly recommended!',
    date: 'Published on June, 2024',
  },
  {
    id: 7,
    name: 'Chris Green',
    rating: 4.0,
    testimony: 'Product quality is fine, but had issues with delivery.',
    date: 'Published on June, 2024',
  },
  {
    id: 8,
    name: 'Emily Scott',
    rating: 4.0,
    testimony: 'Absolutely fantastic experience from start to finish.',
    date: 'Published on June, 2024',
  },
  {
    id: 9,
    name: 'Michael Lee',
    rating: 4.0,
    testimony: 'Good products, but prices could be lower.',
    date: 'Published on June, 2024',
  },
  {
    id: 10,
    name: 'Sarah Miller',
    rating: 4.0,
    testimony: 'Five-star experience! Will definitely recommend.',
    date: 'Published on June, 2024',
  },
  {
    id: 11,
    name: 'Oliver Black',
    rating: 5.0,
    testimony: 'Exceptional customer service and quality. I’ll be back!',
    date: 'Published on June, 2024',
  },
  {
    id: 12,
    name: 'Sophia White',
    rating: 4.5,
    testimony: 'Overall, a good experience. Packaging could be improved.',
    date: 'Published on June, 2024',
  },
];
